# Generated by Django 5.0.1 on 2024-02-04 08:03

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('products', '0005_category_product_quantity_product_category'),
    ]

    operations = [
        migrations.AddField(
            model_name='product',
            name='price_with_discount',
            field=models.PositiveIntegerField(default=0),
        ),
    ]
