# Generated by Django 5.0.1 on 2024-02-06 13:17

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('products', '0008_basketproducts_favoritescategories_favoritesproducts'),
    ]

    operations = [
        migrations.RenameField(
            model_name='basketproducts',
            old_name='total_sum',
            new_name='price',
        ),
    ]
